"""A safety net between ``--autogenerate`` and your production data.

Autogenerate works by diffing ``Base.metadata`` against the live database. That
makes it structurally unable to tell these two cases apart:

* "this table was deliberately removed" -- and should be dropped;
* "this model was not imported" -- and the table must **not** be dropped.

Model discovery (``app.core.discovery``) removes the second case at the source.
This module is the belt to that pair of braces: if a destructive operation ever
escapes autogenerate anyway, generation stops and a human has to opt in.

The guard applies **only to autogenerated directives**. A hand-written migration
that drops a table is unaffected -- deliberate destruction stays easy, accidental
destruction stops being silent.
"""

from __future__ import annotations

import os
from collections.abc import Iterator
from typing import Any

from alembic.operations import ops

from app.logging import get_logger

log = get_logger(__name__)

#: Set ``ALLOW_DESTRUCTIVE=1`` to permit drops in a generated migration.
ALLOW_DESTRUCTIVE_ENV = "ALLOW_DESTRUCTIVE"


class DestructiveMigrationError(RuntimeError):
    """Autogenerate proposed dropping something and was not authorised to."""


def _iter_ops(container: Any) -> Iterator[Any]:
    """Walk a directive tree; ``ModifyTableOps`` nests column operations."""
    for op in getattr(container, "ops", []):
        yield op
        if hasattr(op, "ops"):
            yield from _iter_ops(op)


def _describe(op: Any) -> str | None:
    if isinstance(op, ops.DropTableOp):
        return f"drop_table({op.table_name!r})"
    if isinstance(op, ops.DropColumnOp):
        return f"drop_column({op.table_name!r}, {op.column_name!r})"
    if isinstance(op, ops.DropConstraintOp):
        return f"drop_constraint({op.constraint_name!r} on {op.table_name!r})"
    return None


def reject_destructive_ops(
    context: Any,
    revision: Any,
    directives: list[Any],
    *,
    allow_destructive: bool | None = None,
) -> None:
    """Alembic ``process_revision_directives`` hook.

    Raises :class:`DestructiveMigrationError` if the generated migration would
    drop a table, column or constraint, unless destruction is explicitly allowed.
    """
    if allow_destructive is None:
        allow_destructive = os.environ.get(ALLOW_DESTRUCTIVE_ENV) == "1"

    destructive: list[str] = []
    for directive in directives:
        upgrade_ops = getattr(directive, "upgrade_ops", None)
        if upgrade_ops is None:
            continue
        for op in _iter_ops(upgrade_ops):
            described = _describe(op)
            if described is not None:
                destructive.append(described)

    if not destructive:
        return

    if allow_destructive:
        log.warning(
            "migration.destructive_allowed",
            operations=destructive,
            reason=f"{ALLOW_DESTRUCTIVE_ENV}=1",
        )
        return

    log.error("migration.destructive_blocked", operations=destructive)
    raise DestructiveMigrationError(
        "Autogenerate produced destructive operations and was stopped:\n"
        + "\n".join(f"  - {d}" for d in destructive)
        + "\n\n"
        "The usual cause is a model that was not imported, which makes its table "
        "look deleted. Check that the model lives under a discovered plugin "
        "package before assuming the drop is correct.\n"
        f"If the removal really is intended, re-run with {ALLOW_DESTRUCTIVE_ENV}=1."
    )
