"""stored file metadata

Revision ID: 66fba9fbe2c9
Revises: bbd8c5d2bed5
Create Date: 2026-08-24 12:03:21.522979
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '66fba9fbe2c9'
down_revision: str | None = 'bbd8c5d2bed5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_file',
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_file'))
    )
    op.create_index(op.f('ix_stored_file_checksum_sha256'), 'stored_file', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_stored_file_storage_key'), 'stored_file', ['storage_key'], unique=True)
    op.create_index(op.f('ix_stored_file_uploaded_by'), 'stored_file', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_file_uploaded_by'), table_name='stored_file')
    op.drop_index(op.f('ix_stored_file_storage_key'), table_name='stored_file')
    op.drop_index(op.f('ix_stored_file_checksum_sha256'), table_name='stored_file')
    op.drop_table('stored_file')
    # ### end Alembic commands ###
